server:
  port: 8888  # Config Server will run on this port

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Baidhya/ecommerce-config-repo.git
          clone-on-start: true  # Clones the Git repo when the server starts
          default-label: main  # Specify the branch name

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true


